# Roblox 開発ツールのバージョン固定（https://github.com/rojo-rbx/rokit）
# `rokit install` で下記のツールがインストールされる
[tools]
rojo = "rojo-rbx/rojo@7.7.0"
selene = "Kampfkarren/selene@0.31.0"
stylua = "JohnnyMorganz/StyLua@2.5.2"
